title: Changen Yang
page-top-title: Changen Yang
top-section-bg-text: Robotics Engineering<br>Hainan University
home-subtitle: Changen Yang&ensp;|&ensp;杨常恩
copyright-text: '&copy; Changen Yang 2026. All Rights Reserved.'
